# Generated by Django 5.1.7 on 2025-03-24 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt_Informacii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica', models.CharField(max_length=120)),
                ('br_market', models.IntegerField()),
                ('tel_br', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_proizvod', models.CharField(max_length=120)),
                ('vid', models.CharField(choices=[('HR', 'HRANA'), ('PI', 'PIJALOK'), ('PK', 'PEKARA'), ('KO', 'KOZMETIKA'), ('HI', 'HIGIENA')], max_length=2)),
                ('domashen', models.BooleanField()),
                ('kod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('broj_na_marketi', models.IntegerField()),
                ('datum_otvaranje', models.DateField()),
                ('rabotno_vreme_od', models.DateField()),
                ('rabotno_vreme_do', models.DateField()),
                ('kontakt_informacii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.kontakt_informacii')),
                ('korisnik_dodal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proizvodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.proizvod')),
            ],
        ),
        migrations.CreateModel(
            name='MarketProizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.proizvod')),
            ],
        ),
        migrations.CreateModel(
            name='Vraboten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_vraboten', models.CharField(max_length=120)),
                ('prezime_vraboten', models.CharField(max_length=120)),
                ('EMBG', models.IntegerField()),
                ('plata', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketVraboten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.market')),
                ('vraboten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.vraboten')),
            ],
        ),
        migrations.AddField(
            model_name='market',
            name='vraboten',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.vraboten'),
        ),
    ]
